In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [9]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [10]:
#Changing categorial columns to Binary format by using one-hot encoding
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [11]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [15]:
#Split the input and output
indep=dataset.drop("classification_yes", axis=1)
dep=dataset['classification_yes']

In [17]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score

In [23]:
#======================================
#SVM Model
#======================================
from sklearn.svm import SVC

# Define parameter grid
param_grid_SVC = {
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
    'gamma': ['auto', 'scale'],
    'C': [10, 100, 1000, 2000, 3000]
}

#  Define SVC with probability=True
svc_model = SVC(probability=True)

# Set up GridSearchCV
grid_SVC = GridSearchCV(
    estimator=svc_model,
    param_grid=param_grid_SVC,
    refit=True,
    verbose=3,
    n_jobs=-1,
    scoring='f1_weighted'
)

#  Fit the grid to training data
grid_SVC.fit(X_train, y_train)

#  Predict using the best model
grid_predictions_SVC = grid_SVC.predict(X_test)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


In [25]:

cm_SVC = confusion_matrix(y_test, grid_predictions_SVC)
print("The confusion Matrix:\n",cm_SVC)
clf_report_SVC = classification_report(y_test, grid_predictions_SVC)
re=grid_SVC.cv_results_
table=pd.DataFrame.from_dict(re)
table

The confusion Matrix:
 [[51  0]
 [ 1 81]]


mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.039761      0.012866         0.056831        0.027170       10   
1        0.010495      0.006859         0.005788        0.006658       10   
2        0.012787      0.003905         0.011500        0.006691       10   
3        0.010004      0.001801         0.007324        0.003122       10   
4        0.008808      0.001488         0.005502        0.001568       10   
5        0.014238      0.007655         0.013407        0.006927       10   
6        0.013982      0.003245         0.016027        0.000794       10   
7        0.008007      0.004004         0.002002        0.004004       10   
8        0.004004      0.004904         0.004829        0.006328      100   
9        0.008025      0.008202         0.008575        0.005236      100   
10       0.019910      0.002845         0.009383        0.007662      100   
11       0.011204      0.005840         0.003004        0.004004      100   
12       0.005255      0.004464         0.006251        0.007655      100   
13       0.013273      0.009282         0.009523        0.005148      100   
14       0.012642      0.003182         0.008432        0.005279      100   
15       0.010149      0.006442         0.006613        0.005560      100   
16       0.005008      0.004209         0.008145        0.005217     1000   
17       0.012878      0.003825         0.010046        0.000047     1000   
18       0.024186      0.010307         0.013220        0.009911     1000   
19       0.008230      0.004247         0.006028        0.004922     1000   
20       0.010116      0.000039         0.007057        0.004048     1000   
21       0.007273      0.003794         0.014054        0.006669     1000   
22       0.018262      0.005740         0.005436        0.004582     1000   
23       0.008773      0.004585         0.005021        0.004499     1000   
24       0.007563      0.006465         0.003994        0.004667     2000   
25       0.024331      0.014721         0.013313        0.009188     2000   
26       0.022585      0.008339         0.006896        0.003197     2000   
27       0.013928      0.011414         0.005419        0.003239     2000   
28       0.007976      0.004130         0.007595        0.004769     2000   
29       0.011221      0.002203         0.009761        0.004079     2000   
30       0.018219      0.001769         0.009929        0.003234     2000   
31       0.010228      0.000272         0.011028        0.001835     2000   
32       0.009810      0.000952         0.006918        0.003773     3000   
33       0.011453      0.004600         0.015270        0.010702     3000   
34       0.022055      0.004779         0.008913        0.001422     3000   
35       0.013433      0.006626         0.006342        0.000833     3000   
36       0.008359      0.000816         0.007769        0.002610     3000   
37       0.010378      0.000936         0.010106        0.002970     3000   
38       0.024581      0.006148         0.007530        0.001740     3000   
39       0.010723      0.003234         0.010246        0.004997     3000   

   param_gamma param_kernel  \
0         auto       linear   
1         auto          rbf   
2         auto         poly   
3         auto      sigmoid   
4        scale       linear   
5        scale          rbf   
6        scale         poly   
7        scale      sigmoid   
8         auto       linear   
9         auto          rbf   
10        auto         poly   
11        auto      sigmoid   
12       scale       linear   
13       scale          rbf   
14       scale         poly   
15       scale      sigmoid   
16        auto       linear   
17        auto          rbf   
18        auto         poly   
19        auto      sigmoid   
20       scale       linear   
21       scale          rbf   
22       scale         poly   
23       scale      sigmoid   
24        auto       linear   
25        auto          rbf   
26       

The f1_macro value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}: 0.9924946382275899


In [88]:
# 6. Evaluate the model
f1_macro_SVC=f1_score(y_test,grid_predictions_SVC,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid_SVC.best_params_),f1_macro_SVC)

print("Accuracy for SVC Model:", accuracy_score(y_test, grid_predictions_SVC))
print("Classification Report for SVC Model:\n", clf_report_SVC)

# 7. ROC AUC Score (for binary classification only)
y_proba_SVC = grid_SVC.best_estimator_.predict_proba(X_test)[:, 1]
auc_SVC = roc_auc_score(y_test, y_proba_SVC)
print("ROC AUC Score for SVC:", auc_SVC)

The f1_macro value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}: 0.9924946382275899
Accuracy for SVC Model: 0.9924812030075187
Classification Report for SVC Model:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

ROC AUC Score for SVC: 1.0


In [31]:
#======================================
#Logistic Regression Model
#======================================
from sklearn.linear_model import LogisticRegression

param_grid_Logistic = {'solver':['newton-cg', 'lbfgs', 'liblinear', 'saga'],
             'penalty':['l2']} 

grid_Logistic = GridSearchCV(LogisticRegression(), param_grid_Logistic, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid_Logistic.fit(X_train, y_train) 


Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [33]:
#  Predict using the best model
grid_predictions_Logistic = grid_Logistic.predict(X_test)

In [35]:
cm_logistic = confusion_matrix(y_test, grid_predictions_Logistic)
print("The confusion Matrix:\n",cm_logistic)
# print classification report 
from sklearn.metrics import classification_report
clf_report_logistic = classification_report(y_test, grid_predictions_Logistic)

The confusion Matrix:
 [[51  0]
 [ 1 81]]


In [37]:
f1_macro_Logistic=f1_score(y_test,grid_predictions_Logistic,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid_Logistic.best_params_),f1_macro_Logistic)

# 6. Evaluate the model
print("Accuracy for Logistic Model:", accuracy_score(y_test, grid_predictions_Logistic))
print("Classification Report for Logistic Model:\n", clf_report_logistic)

# 7. ROC AUC Score (for binary classification only)
y_proba_Logistic = grid_Logistic.best_estimator_.predict_proba(X_test)[:, 1]
auc_Logistic = roc_auc_score(y_test, y_proba_Logistic)
print("ROC AUC Score for Logistic:", auc_Logistic)

The f1_macro value for best parameter {'penalty': 'l2', 'solver': 'newton-cg'}: 0.9924946382275899
Accuracy for Logistic Model: 0.9924812030075187
Classification Report for Logistic Model:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

ROC AUC Score for Logistic: 1.0


In [39]:
re=grid_Logistic.cv_results_
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       0.567549      0.260663         0.011378        0.009984            l2   
1       0.160235      0.082531         0.006045        0.004936            l2   
2       0.057927      0.028077         0.005704        0.000191            l2   
3       0.098502      0.044295         0.006330        0.005175            l2   

  param_solver                                    params  split0_test_score  \
0    newton-cg  {'penalty': 'l2', 'solver': 'newton-cg'}           0.981569   
1        lbfgs      {'penalty': 'l2', 'solver': 'lbfgs'}           0.981569   
2    liblinear  {'penalty': 'l2', 'solver': 'liblinear'}           0.963284   
3         saga       {'penalty': 'l2', 'solver': 'saga'}           0.981569   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.981014           0.981217           1.000000           1.000000   
1           0.981014           0.981217           1.000000           1.000000   
2           0.981233           0.962573           0.981217           0.981217   
3           0.981233           0.981217           0.981217           0.981217   

   mean_test_score  std_test_score  rank_test_score  
0         0.988760        0.009179                1  
1         0.988760        0.009179                1  
2         0.973905        0.008965                4  
3         0.981291        0.000139                3

In [42]:
#======================================
#Random Forest Classification Model
#======================================
from sklearn.ensemble import RandomForestClassifier

param_grid_RF = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid_RF = GridSearchCV(RandomForestClassifier(), param_grid_RF, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid_RF.fit(X_train, y_train) 
print(grid_RF.best_params_) 

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_pa

{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}


In [44]:
re_RF=grid_RF.cv_results_
#print(re)
grid_predictions_RF = grid_RF.predict(X_test) 

cm_RF = confusion_matrix(y_test, grid_predictions_RF)
print("The confusion Matrix:\n",cm_RF)
# print classification report 
clf_report_RF = classification_report(y_test, grid_predictions_RF)


The confusion Matrix:
 [[51  0]
 [ 1 81]]


In [46]:
f1_macro_RF=f1_score(y_test,grid_predictions_RF,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid_RF.best_params_),f1_macro_RF)

# 6. Evaluate the model
print("Accuracy for RF Model:", accuracy_score(y_test, grid_predictions_RF))
print("Classification Report for RF Model:\n", clf_report_RF)

# 7. ROC AUC Score (for binary classification only)
y_proba_RF = grid_RF.best_estimator_.predict_proba(X_test)[:, 1]
auc_RF = roc_auc_score(y_test, y_proba_RF)
print("ROC AUC Score for RF:", auc_RF)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.9924946382275899
Accuracy for RF Model: 0.9924812030075187
Classification Report for RF Model:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

ROC AUC Score for RF: 1.0


In [49]:
#======================================
#DecisionTree Classification Model
#======================================
from sklearn.tree import DecisionTreeClassifier
param_grid_DC = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 



grid_DC = GridSearchCV(DecisionTreeClassifier(), param_grid_DC, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid_DC.fit(X_train, y_train) 
 

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_pa

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [51]:
re_DC=grid_RF.cv_results_
#print(re)
grid_predictions_DC = grid_DC.predict(X_test) 

cm_DC = confusion_matrix(y_test, grid_predictions_DC)
print("The confusion Matrix:\n",cm_DC)
# print classification report 
clf_report_DC = classification_report(y_test, grid_predictions_DC)

The confusion Matrix:
 [[51  0]
 [ 3 79]]


In [63]:
f1_macro_DC=f1_score(y_test,grid_predictions_DC,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid_DC.best_params_),f1_macro_DC)

# 6. Evaluate the model
print("Accuracy for DC Model:", accuracy_score(y_test, grid_predictions_DC))
print("Classification Report for DC Model:\n", clf_report_RF)

# 7. ROC AUC Score (for binary classification only)
y_proba_DC = grid_DC.best_estimator_.predict_proba(X_test)[:, 1]
auc_DC = roc_auc_score(y_test, y_proba_DC)
print("ROC AUC Score for DC:", auc_DC)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'best'}: 0.9775556904684072
Accuracy for DC Model: 0.9774436090225563
Classification Report for DC Model:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

ROC AUC Score for DC: 0.9817073170731707


In [57]:
#======================================
#      KNN Model
#======================================
from sklearn.neighbors import KNeighborsClassifier
param_grid_neighbors = {'n_neighbors':[5,10,50],
              'algorithm': ['auto','ball_tree','kd_tree','brute'],
              'metric':['minkowski','callable'],
                       'p':[2,10,15]} 



grid_neighbors = GridSearchCV(KNeighborsClassifier(), param_grid_neighbors, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid_neighbors.fit(X_train, y_train) 

Fitting 5 folds for each of 72 candidates, totalling 360 fits


C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
180 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
53 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'callable'],
                         'n_neighbors': [5, 10, 50], 'p': [2, 10, 15]},
             scoring='f1_weighted', verbose=3)

In [59]:
re_neighbors=grid_neighbors.cv_results_
#print(re)
grid_predictions_neighbors = grid_neighbors.predict(X_test) 

cm_neighbors = confusion_matrix(y_test, grid_predictions_neighbors)
print("The confusion Matrix:\n",cm_neighbors)
# print classification report 
clf_report_neighbors = classification_report(y_test, grid_predictions_neighbors)

The confusion Matrix:
 [[51  0]
 [ 7 75]]


In [61]:
f1_macro_neighbors=f1_score(y_test,grid_predictions_neighbors,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid_neighbors.best_params_),f1_macro_neighbors)

# 6. Evaluate the model
print("Accuracy for KNN Model:", accuracy_score(y_test, grid_predictions_neighbors))
print("Classification Report for KNN Model:\n", clf_report_neighbors)

# 7. ROC AUC Score (for binary classification only)
y_proba_neighbors = grid_neighbors.best_estimator_.predict_proba(X_test)[:, 1]
auc_neighbors= roc_auc_score(y_test, y_proba_neighbors)
print("ROC AUC Score for KNN:", auc_neighbors)

The f1_macro value for best parameter {'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 5, 'p': 10}: 0.9478851104269762
Accuracy for KNN Model: 0.9473684210526315
Classification Report for KNN Model:
               precision    recall  f1-score   support

           0       0.88      1.00      0.94        51
           1       1.00      0.91      0.96        82

    accuracy                           0.95       133
   macro avg       0.94      0.96      0.95       133
weighted avg       0.95      0.95      0.95       133

ROC AUC Score for KNN: 0.9927068388330942


In [86]:
#======================================
#      Naive Bayes Model
#======================================
from sklearn.naive_bayes import MultinomialNB
#Avoid using StandardScaler for NB.This creates negative values, and is more suitable for algorithms like SVM or KNN — not Naive Bayes.
#MinMaxScaler scales features to [0, 1] range, which is safe for MultinomialNB.
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)

classifier = MultinomialNB()
# fitting the model i.e Model Creation
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

cm_NB = confusion_matrix(y_test, y_pred)
print("The confusion Matrix:\n",cm_NB)

# 6. Evaluate the model
print("Accuracy for NB Model:", accuracy_score(y_test, y_pred))
auc_NB= roc_auc_score(y_test, y_pred)
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print("ROC AUC Score for KNN:", auc_NB)



The confusion Matrix:
 [[51  0]
 [23 59]]
Accuracy for NB Model: 0.8270676691729323
              precision    recall  f1-score   support

           0       0.69      1.00      0.82        51
           1       1.00      0.72      0.84        82

    accuracy                           0.83       133
   macro avg       0.84      0.86      0.83       133
weighted avg       0.88      0.83      0.83       133

ROC AUC Score for KNN: 0.8597560975609756


In [55]:
#As per our analysis Support Vector Classification and Logistic Regression is Best Model
#Saved the best Model .
import pickle
filename = 'finalized_Classification_model.sav'
pickle.dump(grid_SVC.best_estimator_, open(filename, 'wb'))